services:
  ytdlp2strm:
    build: .
    container_name: ytdlp2STRM
    environment:
      - AM_I_IN_A_DOCKER_CONTAINER=Yes
      - DOCKER_PORT=5005 #this will be put into the .strm file
      - TZ=America/New_York
    volumes:
      - ./dev/media:/media
      - ytdlp2strm-data:/opt/ytdlp2STRM
      - ./config/crons.example.json:/opt/ytdlp2STRM/config/crons.json
      - ./config/config.example.json:/opt/ytdlp2STRM/config/config.json
    ports:
      - 5005:5000
    restart: always

volumes:
  ytdlp2strm-data:
